Proyecto/Models/Rol.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.RolPagina = new HashSet<RolPagina>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IIDROL { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolPagina> RolPagina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}

Proyecto/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class RolController : Controller
    {
        // GET: Rol
        public ActionResult Index()
        {
            List<RolCLS> lista = new List<RolCLS>();
            using (var bd = new BDPasajeEntities())
            {
                lista = (from rol in bd.Rol
                         where rol.BHABILITADO == 1
                         select new RolCLS
                         {
                             iidRol = rol.IIDROL,
                             nombre = rol.NOMBRE,
                             descripcion = rol.DESCRIPCION
                         }).ToList();
            }
            return View(lista);
        }
        public ActionResult Filtro(string nombreRol)
        {
            List<RolCLS> lista = new List<RolCLS>();
            if (nombreRol == null)
            {
                using (var db = new BDPasajeEntities())
                {
                    lista = (from rol in db.Rol
                             where rol.BHABILITADO == 1
                             select new RolCLS
                             {
                                 iidRol = rol.IIDROL,
                                 nombre = rol.NOMBRE,
                                 descripcion = rol.DESCRIPCION
                             }
                             ).ToList();
                }
            }
            else
            {
                using (var db = new BDPasajeEntities())
                {
                    lista = (from rol in db.Rol
                             where rol.BHABILITADO == 1 && rol.NOMBRE.Contains(nombreRol)
                             select new RolCLS
                             {
                                 iidRol = rol.IIDROL,
                                 nombre = rol.NOMBRE,
                                 descripcion = rol.DESCRIPCION
                             }
                             ).ToList();
                }
            }
            return PartialView("_TablaRol", lista);
        }
        public string Guardar(RolCLS oRolCLS, int titulo)
        {
            string respuesta = "";
            try
            {
                if (!ModelState.IsValid)
                {
                    var query = (from state in ModelState.Values
                                 from error in state.Errors
                                 select error.ErrorMessage).ToList();
                    respuesta += "<ul class='list-group'>";
                    foreach (var item in query)
                    {
                        respuesta += "<li class='list-group-item'>" + item + "</li>";
                    }
                    respuesta += "</ul>";

                }
                else
                {
                    using (var db = new BDPasajeEntities())
                    {
                        if (titulo.Equals(-1))
                        {
                            Rol oRol = new Rol();
                            oRol.NOMBRE = oRolCLS.nombre;
                            oRol.DESCRIPCION = oRolCLS.descripcion;
                            oRol.BHABILITADO = 1;
                            db.Rol.Add(oRol);
                            respuesta = db.SaveChanges().ToString();
                            if (respuesta == "0") respuesta = "";
                            
                        }
                        else
                        {
                            Rol oRol = db.Rol.Where(p => p.IIDROL == titulo).First();
                            oRol.NOMBRE = oRolCLS.nombre;
                            oRol.DESCRIPCION = oRolCLS.descripcion;
                            respuesta = db.SaveChanges().ToString();

                        }
                    }
                }
            }
            catch(Exception ex)
            {
                respuesta = "";
            }
            return respuesta; 
        } 
        public JsonResult recuperarDatos(int titulo)
        {
            RolCLS oRolCLS = new RolCLS();
            using (var db = new BDPasajeEntities())
            {
                Rol oRol = db.Rol.Where(p => p.IIDROL == titulo).First();
                oRolCLS.nombre = oRol.NOMBRE;
                oRolCLS.descripcion = oRol.DESCRIPCION;
            }
            return Json(oRolCLS,JsonRequestBehavior.AllowGet);
        }
    }
}

Proyecto/Views/Rol/Index.cshtml
@using Proyecto.Models
@model List<RolCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<button type="button" onclick="Agregar();" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalScrollable">
Agregar
</button>
@using (Ajax.BeginForm("Filtro", "", new AjaxOptions {
    HttpMethod = "POST",
    UpdateTargetId = "divRol",
    InsertionMode=InsertionMode.Replace
},new { @id="frmFiltro"}))
{
    @Html.Label("Ingrese nombre rol")
    @Html.TextBox("nombreRol", null,new { @class="form-control"})
    <div id="divRol">
        @Html.Partial("_TablaRol", Model);
    </div>
}



<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalScrollableTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
             @using (Ajax.BeginForm("Guardar", "Rol",null, new AjaxOptions
             {
                 HttpMethod = "POST",
                 OnSuccess = "Guardar",
                 UpdateTargetId="error"
             }))
             {
                  @Html.Hidden("titulo")
            <div class="modal-body">
                <div>
                    @Html.Label("Nombre");
                    @Html.TextBox("nombre", null, new { @class = "form-control" })
                </div> 
                <div>
                    @Html.Label("Descripción")
                    @Html.TextBox("descripcion", null, new { @class = "form-control" })
                </div>
              </div>
            <div class="modal-footer">
                <button id="btnClose" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
             }
            <div id="error"></div>
        </div>
    </div>
</div>
<script>
    var nombre = document.getElementById("nombre")
    nombre.onkeyup = function () {
        $("#frmFiltro").trigger("submit");
    }
    function Limpiar() {
        document.getElementById("nombre").value = "";
        document.getElementById("descripcion").value = "";
        document.getElementById("error").innerHTML = "";
    }
    function Agregar() {
        Limpiar();
        document.getElementById("titulo").value= -1;
    }
    function Editar(id) {
        Limpiar();
        document.getElementById("titulo").value = id;

        $.get("Rol/recuperarDatos/?titulo=" + id, function (data) {
            document.getElementById("nombre").value = data.nombre;
            document.getElementById("descripcion").value = data.descripcion;
        })
    }
    function Guardar(resultado) {
        if (resultado == "1" || resultado=="0") {
            $("#frmFiltro").trigger("submit");
            document.getElementById("btnClose").click();
            alert("Se guardo correctamente");
        }
        else {
            alert("Ocurrio un error");
        }
    }
</script>

Proyecto/Views/Rol/_TablaRol.cshtml
@using Proyecto.Models
@model List<RolCLS>

<table class="table table-bordered table-hover" >
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidRol)</td>
            <td>@Html.LabelFor(p => Model[0].nombre)</td>
            <td>@Html.LabelFor(p => Model[0].descripcion)</td>
            <td>Operaciones </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidRol</td>
                <td>@item.nombre</td>
                <td>@item.descripcion</td>
                <td><button type="button" onclick="Editar(@item.iidRol);" class="btn btn-primary glyphicon glyphicon-edit"  data-toggle="modal" data-target="#exampleModalScrollable"></button>
                 </td>
            </tr>

        }
    </tbody>

</table>