Proyecto/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

Proyecto/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.Models;

namespace Proyecto.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index(MarcaCLS oMarcaCLS)
        {
            List<MarcaCLS> listaMarca = null;
            using (var bd = new BDPasajeEntities())
            {

                if (oMarcaCLS.nombre == null)
                {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1
                                  select new MarcaCLS
                                  {
                                      iidmarca = marca.IIDMARCA,
                                      nombre = marca.NOMBRE,
                                      descripcion = marca.DESCRIPCION
                                  }).ToList();
                }
                else
                {
                    listaMarca = (from marca in bd.Marca
                                  where marca.BHABILITADO == 1 && marca.NOMBRE.Contains(oMarcaCLS.nombre)
                                  select new MarcaCLS
                                  {
                                      iidmarca = marca.IIDMARCA,
                                      nombre=marca.NOMBRE,
                                      descripcion=marca.DESCRIPCION
                                  }).ToList();
                }
            }
            
                return View(listaMarca);
        }
        public ActionResult Agregar()
        {
           
            return View();
        }
        public ActionResult Editar(int id)
        {
            MarcaCLS oMarcaCLS = new MarcaCLS();
            using (var db = new BDPasajeEntities())
            {
                Marca oMarca = db.Marca.Where(p => p.IIDMARCA.Equals(id)).First();
                oMarcaCLS.iidmarca = oMarca.IIDMARCA;
                oMarcaCLS.nombre = oMarca.NOMBRE;
                oMarcaCLS.descripcion = oMarca.DESCRIPCION;
            }
                return View(oMarcaCLS);
        }
        
        [HttpPost]
        public ActionResult Agregar(MarcaCLS oMarcaCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreMarca = oMarcaCLS.nombre;
            using(var db = new BDPasajeEntities())
            {
                nregistrosEncontrados = db.Marca.Where(p => p.NOMBRE.Equals(nombreMarca)).Count();
            }
            
            if (!ModelState.IsValid || nregistrosEncontrados>0)
            {
                if (nregistrosEncontrados > 0) oMarcaCLS.mensajeError = "El nombre marca ya existe";
                return View(oMarcaCLS);
            }
            else
            {
                using(var db = new BDPasajeEntities())
                {
                    Marca oMarca = new Marca();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    oMarca.BHABILITADO = 1;
                    db.Marca.Add(oMarca);
                    db.SaveChanges();
                }

            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Editar(MarcaCLS oMarcaCLS)
        {
            int n=0;
            string nombre = oMarcaCLS.nombre;
            int id = oMarcaCLS.iidmarca;
            using(var db = new BDPasajeEntities())
            {
                n = db.Marca.Where(p => p.NOMBRE.Equals(nombre) && !p.IIDMARCA.Equals(id)).Count(); 
            }
            if (!ModelState.IsValid || n>0)
            {
                if (n > 0) oMarcaCLS.mensajeError = "Ya existe esta marca";
                return View(oMarcaCLS);
            }
            else
            {
                int idMarca = oMarcaCLS.iidmarca;
                using (var db = new BDPasajeEntities())
                {
                    Marca oMarca = db.Marca.Where(p => p.IIDMARCA.Equals(idMarca)).First();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.DESCRIPCION = oMarcaCLS.descripcion;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        public ActionResult Eliminar(int id)
        {
            using(var db =new BDPasajeEntities())
            {
                Marca oMarca = db.Marca.Where(p => p.IIDMARCA.Equals(id)).First();
                oMarca.BHABILITADO = 0;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Proyecto/Views/Marca/Agregar.cshtml
@using Proyecto.Models
@model MarcaCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post,new {@id="frmAgregar"}))
        {
        <div>
        @Html.LabelFor(p=>p.nombre)
        @Html.TextBoxFor(p => p.nombre,new { @class="form-control"})
        @Html.ValidationMessage("nombre",new { @class="text-danger"})
            @if(Model!=null&&Model.mensajeError != null)
            {
                @Html.Label(Model.mensajeError,new {@class="text-danger" })
            }
        </div>
        <div>
            @Html.LabelFor(p => p.descripcion)
            @Html.EditorFor(p => p.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("descripcion", new { @class = "text-danger" })


        </div>
        <br />
        <div style="margin:auto">
            <input type="submit" class="btn btn-primary"value="Guardar" />
            @Html.ActionLink("Cancelar", "Index", "Marca", null,new {@class="btn btn-danger"})
        </div>
        }
    </div>
</div>
<script>
    var frmAgregar = document.getElementById("frmAgregar");
    frmAgregar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            frmAgregar.submit();
        }
    }
</script>

Proyecto/Views/Marca/Editar.cshtml
@using Proyecto.Models
@model MarcaCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Marca", FormMethod.Post, new { @id = "frmEditar" }))
        {
            <div>
                @Html.LabelFor(p => p.iidmarca)
                @Html.TextBoxFor(p => p.iidmarca, new { @class = "form-control", @readOnly = true })
                @Html.ValidationMessage("iidmarca", new { @class = "text-danger" })
               
            </div>
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion)
                @Html.EditorFor(p => p.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>
            <br />
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Cancelar", "Index", "Marca", null,new { @class="btn btn-danger"})
            </div>
        }
    </div>
</div>
<script>
    var frmEditar = document.getElementById("frmEditar");
    frmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            frmEditar.submit();
        }
    }
</script>

Proyecto/Views/Marca/Index.cshtml
@using Proyecto.Models
@model List<MarcaCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Marcas</h2>
@Html.ActionLink("Agregar","Agregar","Marca",null,new {@class="btn btn-primary" })

@using (Html.BeginForm("Index", "Marca", FormMethod.Post))
{
@Html.Label("Ingrese nombre marca")
@Html.TextBox("nombre")
<input type="submit" class="btn btn-success" value="Buscar"/>
}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td width="10%">@Html.LabelFor(p=>Model[0].iidmarca)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].nombre)</td>
            <td width="60%">@Html.LabelFor(p => Model[0].descripcion)</td>
            <td width="10%">Operaciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.iidmarca</td>
                <td>@item.nombre</td>
                <td>@item.descripcion</td>
                <td>
                    @Html.ActionLink(" ","Editar","Marca",new {id=@item.iidmarca},new { @class = "glyphicon glyphicon-edit btn btn-primary " })
                    @Html.ActionLink(" ", "Eliminar", "Marca", new { id = @item.iidmarca }, new { @class = "glyphicon glyphicon-trash btn btn-danger",@onclick="Eliminar()" })
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function Eliminar() {
        if (confirm("¿Deseas eliminar el registro") == 1) {
            alert("Se elimino");
        }else
        {
            event.preventDefault();
        }
    }
</script>