Proyecto/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

Proyecto/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.Models;
namespace Proyecto.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index(SucursalCLS oSucursalCLS)
        {
            List<SucursalCLS> listaSucursal = null;
            using (var db = new BDPasajeEntities())
            {
                if (oSucursalCLS.nombre == null)
                {
                    listaSucursal = (from sucursal in db.Sucursal
                                     where sucursal.BHABILITADO == 1
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL

                                     }).ToList();
                }else
                {
                    listaSucursal = (from sucursal in db.Sucursal
                                     where sucursal.BHABILITADO==1 && sucursal.NOMBRE.Contains(oSucursalCLS.nombre)
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL

                                     }).ToList();
                }
            }
            return View(listaSucursal);
        }
        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            int n=0;
            string nombre = oSucursalCLS.nombre;
            using (var db = new BDPasajeEntities())
            {
                n = db.Marca.Where(p => p.NOMBRE.Equals(nombre)).Count();
            }
            if (!ModelState.IsValid || n>0)
            {
                if (n > 0) oSucursalCLS.mensajeError = "Ya existe esta sucursal";
                return View(oSucursalCLS);
            }
            else
            {

                using (var db = new BDPasajeEntities())
                {
                    Sucursal oSucursal = new Sucursal();
                    oSucursal.NOMBRE = oSucursalCLS.nombre;
                    oSucursal.DIRECCION = oSucursalCLS.direccion;
                    oSucursal.TELEFONO = oSucursalCLS.telefono;
                    oSucursal.EMAIL = oSucursalCLS.email;
                    oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                    oSucursal.BHABILITADO = 1;
                    db.Sucursal.Add(oSucursal);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        public ActionResult Editar(int id)
        {
            SucursalCLS oSucursalCLS = new SucursalCLS();
            using (var db = new BDPasajeEntities())
            {
                Sucursal oSucursal = db.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursalCLS.iidsucursal = oSucursal.IIDSUCURSAL;
                oSucursalCLS.nombre = oSucursal.NOMBRE;
                oSucursalCLS.direccion = oSucursal.DIRECCION;
                oSucursalCLS.telefono = oSucursal.TELEFONO;
                oSucursalCLS.email = oSucursal.EMAIL;
                oSucursalCLS.fechaApertura = (DateTime)oSucursal.FECHAAPERTURA;

            }
            return View(oSucursalCLS);
        }
        [HttpPost]
        public ActionResult Editar(SucursalCLS oSucursalCLS)
        {
            int n = 0;
            string nombre=oSucursalCLS.nombre;
            int id = oSucursalCLS.iidsucursal;
            using (var db = new BDPasajeEntities())
            {
                n = db.Sucursal.Where(p => p.NOMBRE.Equals(nombre)&& !p.IIDSUCURSAL.Equals(id)).Count();
            }
                if (!ModelState.IsValid || n>0)
                {
                if (n > 0) oSucursalCLS.mensajeError = "Ya existe esta sucursal";
                    return View(oSucursalCLS);
                } else
                {
                    using (var db = new BDPasajeEntities())
                    {
                        Sucursal oSucursal = db.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                        oSucursal.NOMBRE = oSucursalCLS.nombre;
                        oSucursal.DIRECCION = oSucursalCLS.direccion;
                        oSucursal.TELEFONO = oSucursalCLS.telefono;
                        oSucursal.EMAIL = oSucursalCLS.email;
                        oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
        }
        public ActionResult Eliminar(int id)
        {
            using(var db = new BDPasajeEntities())
            {
                Sucursal oSucursal = db.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursal.BHABILITADO = 0;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Proyecto/Views/Sucursal/Agregar.cshtml
@using Proyecto.Models
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post, new { @id = "FrmSucursal" }))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if(Model!=null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError,new { @class="text-danger"})
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Cancelar", "Index", "Sucursal", null, new {@class="btn btn-danger" })
            </div>
        }
    </div>
</div>
<script>
    var FrmAgregar = document.getElementById("FrmSucursal");
    FrmAgregar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar estos datos?") == 1) {
            FrmAgregar.submit();
        }
    }
</script>

Proyecto/Views/Sucursal/Editar.cshtml
@using Proyecto.Models
@model SucursalCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Sucursal", FormMethod.Post,new {@id="FrmSucursal" }))
        {
            <div>
                @Html.LabelFor(p => p.iidsucursal)
                @Html.TextBoxFor(p => p.iidsucursal, new { @class = "form-control", @readOnly = true })
                @Html.ValidationMessage("iidsucursal", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if(Model !=null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError,new { @class="text-danger"})
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>
            <div style="margin:auto">
                <input type="submit" class="btn btn-primary" value="Guardar" />
                @Html.ActionLink("Regresar","Index","Sucursal",new {@class="btn btn-danger" })
            </div>
        }
    </div>
</div>
<script>
    var FrmEditar = document.getElementById("FrmSucursal");
    FrmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("¿Deseas guardar los cambios?") == 1) {
            FrmEditar.submit();
        }
    }
</script>

Proyecto/Views/Sucursal/Index.cshtml
@using Proyecto.Models
@model List<SucursalCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Sucursal</h2>
@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })
@using (Html.BeginForm("Index", "Sucursal", FormMethod.Get, new { @id = "frm" }))
{
@Html.Label("Ingrese nombre de sucursal");
@Html.TextBox("nombre");

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidsucursal)</td>
            <td>@Html.LabelFor(p => Model[0].nombre)</td>
            <td>@Html.LabelFor(p => Model[0].telefono)</td>
            <td>@Html.LabelFor(p => Model[0].email)</td>
            <td>Operaciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidsucursal</td>
                <td>@item.nombre </td>
                <td>@item.telefono</td>
                <td>@item.email</td>
                <td>
                    @Html.ActionLink(" ", "Editar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "glyphicon glyphicon-edit btn btn-primary " })
                    @Html.ActionLink(" ", "Eliminar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "glyphicon glyphicon-trash btn btn-danger", @onclick = "Eliminar()" }) 
                    </td>
            </tr>
        }
    </tbody>
</table>
}
<script>
    function Eliminar() {
        if (confirm("¿Deseas eliminar?") == 1) {
            alert("Se elimino");
        } else {
            event.preventDefault();
        }
    }
    var nombre = document.getElementById("nombre");
    nombre.onkeyup = function () {
        var frm = document.getElementById("frm");
        frm.submit();
    }
</script>